# 当前的环境配置
spring:
  profiles:
    active: dev

# MyBatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.highedu.cat.pojo.entity; cn.highedu.cat.pojo.dto; cn.highedu.cat.pojo.vo



